name: LambdaAntiCheat
version: 1.0
main: pl.lambdathedev.lambdaanticheat.LambdaAntiCheat
api-version: 1.16
authors: [ LambdaTheDev ]
description: Amateur anti cheat plugin for MC 1.16.4
website: https://github.com/LambdaTheDev/LambdaAntiCheat
